### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by macsupport** [rpnzl/jquery-lazyjson#1]
It looks like this is not in development any more but I thought I would ask a question about the template. I have a structure like this:

```
   <ul id="imageGallery">
    <!-- template -->
    <li id="template-imageGallery" class="light" data-thumb="{{slide.thumb}}" data-iframe=" {{slide.iframe}}" data-src="{{slide.Ssrc}}" data-sub-html="{{slide.subhtml}}" data-description=" {{slide.description}}">
    <img data-thumb="{{slide.thumb}}" class="img-responsive" src="{{slide.thumb}}" alt="{{slide.label}}" /> </li>      
  <!-- /template --> 
  </ul>  
```

My problem is I need the 'li' to contain json data as well. Is there a way to do this or am I stuck?

**Comment by rpnzl** [comment]
Hey! Yes, it's been out of development for a while. I'm not clear on what exactly you need, the `<li>` to contain tags beyond the `<img>` tag? e.g.

``` html
<li data-thumb="{{slide.thumb}}">
  <!-- <img> and text within the <li> -->
  <img data-thumb="{{slide.thumb}}">
  {{slide.label}}
</li>
```

**Comment by macsupport** [comment]
Sorry, I was not clear. When the plugin runs, it does not process the the template code within  the id="template-imagegallery" line, only the img template code. The following code:

```
<li id="template-imageGallery" class="light" data-thumb="{{slide.thumb}}" data-iframe=" {{slide.iframe}}" data-src="{{slide.Ssrc}}" data-sub-html="{{slide.subhtml}}" data-description=" {{slide.description}}">
```

remains the same, so data-thumb="{{slide.thumb}}" remains data-thumb="{{slide.thumb}}" rather than data-thumb="thumb/img1.jpg".

**Comment by rpnzl** [comment]
Ah I see. Unfortunately I think you're stuck in terms of getting that to work with the plugin in it's current state - the template system is extremely limited. You may consider moving all of your `data-...` attributes onto the `<img>` within the `<li>` element, and just targeting the `<img>` instead of the `<li>` itself?

**Comment by macsupport** [comment]
That's what I thought. Won't work in my case do to the structure of the carousel. I appreciate your time to answer!
