### ISSUE TITLE
Parse Json conflicts with twig template engine

### ISSUE THREAD

**Issue by bmnepali** [rpnzl/jquery-lazyjson#12]
Use of '{{ variable }}' to display the parsed json object's data conflicts with twig template engine's '{{ variable }}' syntax

**Comment by rpnzl** [comment]
You'll need to escape those variables to avoid a conflict, take a look at the [Twig's recommended escape methods](http://twig.sensiolabs.org/doc/templates.html#escaping).

**Comment by bmnepali** [comment]
Sorry! but it didn't worked that for me. I've changed the '{{ data }}' to '-- data--' in the respected file and used it...it is working fine! thanks!
