### ISSUE TITLE
How to make this work with jquery mobile

### ISSUE THREAD

**Issue by tigerwil** [rpnzl/jquery-lazyjson#4]
This works as regular html+jQuery
&lt;ul id="buttons"&gt;
    &lt;li id="template-buttons" style="display:none;"&gt;
        &lt;span&gt;{{value}}&lt;/span&gt;
    </li>
&lt;/ul>

But when converted to jQuery Mobile Listview, it does not work any more:
&lt;ul id="buttons" data-role="listview"&gt;
    &lt;li id="template-buttons" style="display:none;"&gt;
        &lt;span>{{value}}&lt;/span&gt;
    &lt;/li&gt;
&lt;/ul>

This is the js code
$( 'ul#buttons').lazyjson({
        loaderImg: 'js/libs/jquery-mobile/images/ajax-loader.gif',
        effect: 'slideDown',
        pagination: {
            active: true,
            pages: 1,
            count: 10
        },
        api: {
            uri: 'http://gd.geobytes.com/AutoCompleteCity?q=phi'
        }
    });

Any Ideas?

**Comment by rpnzl** [comment]
I believe jQuery Mobile does quite a bit of DOM manipulation and bootstrapping based on the `role` attribute (and probably more), so it's very possible it's overriding some of this plugin's required HTML structure. I'd take a look at the DOM in Chrome's inspector or something to look for dynamic updates made by jQuery Mobile.

**Comment by ottz0** [comment]
Thanks for your response

Yes, I think you are right...this is what I suspected

**Comment by tigerwil** [comment]
Ok, I had an idea that it may be something like that, thanks for your quick
reply.

Marc

On Sat, Mar 14, 2015 at 12:57 PM, Michael Giuliana <notifications@github.com
