### ISSUE TITLE
How to handle HTTPS JSON URLs error so-called mixed content

### ISSUE THREAD

**Issue by datamaskin** [rpnzl/jquery-lazyjson#5]
I have recently cloned and scraped the origina rpnzl.com site in an attempt to copy your JSON lazy loading portion of your lasyjson DEMO.

The error returned was the result of so-called mixed content: HTTPS scheme with http URLs in the content i.e.
<code>api: http://rpnzl.com/api/names</code>

Will cause the error. Is there a workaround?

**Comment by rpnzl** [comment]
I'm guessing you're running the library on a site that being served over SSL i.e. HTTPS? If that's the case, any other resources you include on the page must also be HTTPS or your browser will reject the request for security reasons -- the easiest thing to do (in Chrome) is to [allow the site allow the site to load unsafe scripts](https://support.google.com/chrome/answer/1342714?hl=en). You could also move your testing to a server that responds to plain HTTP requests, or use an API endpoint that responds via HTTPS. Good luck!
