### ISSUE TITLE
Showing -  invalid name: "invalidMainElement", type: "error", data: "The main object [object Object] does not exist.

### ISSUE THREAD

**Issue by harish-moghe** [rpnzl/jquery-lazyjson#7]
Showing  following error

name: "invalidMainElement", type: "error", data: "The main object [object Object] does not exist.

JSON API output :

[{"id":557,"data":{"li_class":"top_none ","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo3.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo3.jpg&w=300&h=250&zc=1","post_title":"Test New gallery"}},{"id":293,"data":{"li_class":"top_none ","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo11.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo11.jpg&w=300&h=250&zc=1","post_title":"gallery 6"}},{"id":292,"data":{"li_class":"top_none third","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo2.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo2.jpg&w=300&h=250&zc=1","post_title":"gallery 5"}},{"id":291,"data":{"li_class":"top_none ","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo3.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo3.jpg&w=300&h=250&zc=1","post_title":"gallery 4"}},{"id":290,"data":{"li_class":"top_none ","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo11.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo11.jpg&w=300&h=250&zc=1","post_title":"gallery 3"}},{"id":289,"data":{"li_class":"top_none third","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/10\/gallery_thumb12.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/10\/gallery_thumb12.jpg&w=300&h=250&zc=1","post_title":"gallery 2"}},{"id":18,"data":{"li_class":"top_none ","photo_image":"http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo11.jpg","pimage":"http:\/\/emaratfm.wpengine.com\/wp-content\/themes\/adrn\/timthumb.php?src=http:\/\/emaratfm.wpengine.com\/wp-content\/uploads\/2014\/09\/photo11.jpg&w=300&h=250&zc=1","post_title":"adrn gallery"}}]

**Comment by rpnzl** [comment]
I think I'll need more context -- how LazyJSON is being initialized on the page (include an HTML and JS snippet).
