### ISSUE TITLE
Using responsive equal height grid

### ISSUE THREAD

**Issue by sushantexp** [rpnzl/jquery-lazyjson#8]
Hello,

I am using lazyjson and responsive equal height grid https://github.com/Sam152/Javascript-Equal-Height-Responsive-Rows plugin. I am also using bootstrap for my site. When using lazyjson the equal height is not applying for rows. I am using two column row layout. Can you help me for solving the issue as the website is live and client needs solution ASAP. Please check http://www.turjenter.no/blogg/ link.

Thanks,
Sushant Khadilkar

**Comment by rpnzl** [comment]
Let me know if you still need some help, I'll close this for now.
